// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqifkTyFE8qsRMhW3et84wvoqOyuUggE',
    appId: '1:233388633087:web:0105ac476974e9367c95ca',
    messagingSenderId: '233388633087',
    projectId: 'chat-app-85113',
    authDomain: 'chat-app-85113.firebaseapp.com',
    storageBucket: 'chat-app-85113.appspot.com',
    measurementId: 'G-XP93HTHC6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEGqU4DMArQ-TsGWDZUlab708-4ioBrU',
    appId: '1:233388633087:android:7a9eb9a2e6de6e547c95ca',
    messagingSenderId: '233388633087',
    projectId: 'chat-app-85113',
    storageBucket: 'chat-app-85113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzSjvBqz9u0aM03CVQnD5i63UtrTjam7E',
    appId: '1:233388633087:ios:f1f3b40ff206f7c47c95ca',
    messagingSenderId: '233388633087',
    projectId: 'chat-app-85113',
    storageBucket: 'chat-app-85113.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzSjvBqz9u0aM03CVQnD5i63UtrTjam7E',
    appId: '1:233388633087:ios:58ad445b7687f8d07c95ca',
    messagingSenderId: '233388633087',
    projectId: 'chat-app-85113',
    storageBucket: 'chat-app-85113.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
